<?php
/**
 * AllOfsuccessLinksTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AllOfsuccessLinksTest Class Doc Comment
 *
 * @category    Class
 * @description Link members related to the primary data.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AllOfsuccessLinksTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AllOfsuccessLinks"
     */
    public function testAllOfsuccessLinks()
    {
    }

    /**
     * Test attribute "first"
     */
    public function testPropertyFirst()
    {
    }

    /**
     * Test attribute "last"
     */
    public function testPropertyLast()
    {
    }

    /**
     * Test attribute "prev"
     */
    public function testPropertyPrev()
    {
    }

    /**
     * Test attribute "next"
     */
    public function testPropertyNext()
    {
    }
}
