<?php
/**
 * CurrencyJsonApiRelationshipsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CurrencyJsonApiRelationshipsTest Class Doc Comment
 *
 * @category    Class
 * @description CurrencyJsonApiRelationships
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CurrencyJsonApiRelationshipsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CurrencyJsonApiRelationships"
     */
    public function testCurrencyJsonApiRelationships()
    {
    }

    /**
     * Test attribute "sales_channel_default_assignments"
     */
    public function testPropertySalesChannelDefaultAssignments()
    {
    }

    /**
     * Test attribute "orders"
     */
    public function testPropertyOrders()
    {
    }

    /**
     * Test attribute "sales_channels"
     */
    public function testPropertySalesChannels()
    {
    }

    /**
     * Test attribute "sales_channel_domains"
     */
    public function testPropertySalesChannelDomains()
    {
    }

    /**
     * Test attribute "promotion_discount_prices"
     */
    public function testPropertyPromotionDiscountPrices()
    {
    }

    /**
     * Test attribute "product_exports"
     */
    public function testPropertyProductExports()
    {
    }

    /**
     * Test attribute "country_roundings"
     */
    public function testPropertyCountryRoundings()
    {
    }
}
