<?php
/**
 * MailtemplateSendBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MailtemplateSendBodyTest Class Doc Comment
 *
 * @category    Class
 * @description MailtemplateSendBody
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MailtemplateSendBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MailtemplateSendBody"
     */
    public function testMailtemplateSendBody()
    {
    }

    /**
     * Test attribute "recipients"
     */
    public function testPropertyRecipients()
    {
    }

    /**
     * Test attribute "sales_channel_id"
     */
    public function testPropertySalesChannelId()
    {
    }

    /**
     * Test attribute "content_html"
     */
    public function testPropertyContentHtml()
    {
    }

    /**
     * Test attribute "content_plain"
     */
    public function testPropertyContentPlain()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "sender_name"
     */
    public function testPropertySenderName()
    {
    }

    /**
     * Test attribute "sender_email"
     */
    public function testPropertySenderEmail()
    {
    }

    /**
     * Test attribute "media_ids"
     */
    public function testPropertyMediaIds()
    {
    }

    /**
     * Test attribute "bin_attachments"
     */
    public function testPropertyBinAttachments()
    {
    }

    /**
     * Test attribute "recipients_bcc"
     */
    public function testPropertyRecipientsBcc()
    {
    }

    /**
     * Test attribute "recipients_cc"
     */
    public function testPropertyRecipientsCc()
    {
    }

    /**
     * Test attribute "reply_to"
     */
    public function testPropertyReplyTo()
    {
    }

    /**
     * Test attribute "return_path"
     */
    public function testPropertyReturnPath()
    {
    }
}
