<?php
/**
 * MediaJsonApiRelationshipsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MediaJsonApiRelationshipsTest Class Doc Comment
 *
 * @category    Class
 * @description MediaJsonApiRelationships
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MediaJsonApiRelationshipsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MediaJsonApiRelationships"
     */
    public function testMediaJsonApiRelationships()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "thumbnails"
     */
    public function testPropertyThumbnails()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {
    }

    /**
     * Test attribute "product_manufacturers"
     */
    public function testPropertyProductManufacturers()
    {
    }

    /**
     * Test attribute "product_media"
     */
    public function testPropertyProductMedia()
    {
    }

    /**
     * Test attribute "avatar_user"
     */
    public function testPropertyAvatarUser()
    {
    }

    /**
     * Test attribute "media_folder"
     */
    public function testPropertyMediaFolder()
    {
    }

    /**
     * Test attribute "property_group_options"
     */
    public function testPropertyPropertyGroupOptions()
    {
    }

    /**
     * Test attribute "mail_template_media"
     */
    public function testPropertyMailTemplateMedia()
    {
    }

    /**
     * Test attribute "document_base_configs"
     */
    public function testPropertyDocumentBaseConfigs()
    {
    }

    /**
     * Test attribute "shipping_methods"
     */
    public function testPropertyShippingMethods()
    {
    }

    /**
     * Test attribute "payment_methods"
     */
    public function testPropertyPaymentMethods()
    {
    }

    /**
     * Test attribute "product_configurator_settings"
     */
    public function testPropertyProductConfiguratorSettings()
    {
    }

    /**
     * Test attribute "order_line_items"
     */
    public function testPropertyOrderLineItems()
    {
    }

    /**
     * Test attribute "cms_blocks"
     */
    public function testPropertyCmsBlocks()
    {
    }

    /**
     * Test attribute "cms_sections"
     */
    public function testPropertyCmsSections()
    {
    }

    /**
     * Test attribute "cms_pages"
     */
    public function testPropertyCmsPages()
    {
    }

    /**
     * Test attribute "documents"
     */
    public function testPropertyDocuments()
    {
    }

    /**
     * Test attribute "app_payment_methods"
     */
    public function testPropertyAppPaymentMethods()
    {
    }
}
