<?php
/**
 * OrderJsonApiPriceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderJsonApiPriceTest Class Doc Comment
 *
 * @category    Class
 * @description OrderJsonApiPrice
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderJsonApiPriceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderJsonApiPrice"
     */
    public function testOrderJsonApiPrice()
    {
    }

    /**
     * Test attribute "net_price"
     */
    public function testPropertyNetPrice()
    {
    }

    /**
     * Test attribute "total_price"
     */
    public function testPropertyTotalPrice()
    {
    }

    /**
     * Test attribute "calculated_taxes"
     */
    public function testPropertyCalculatedTaxes()
    {
    }

    /**
     * Test attribute "tax_rules"
     */
    public function testPropertyTaxRules()
    {
    }

    /**
     * Test attribute "position_price"
     */
    public function testPropertyPositionPrice()
    {
    }

    /**
     * Test attribute "raw_total"
     */
    public function testPropertyRawTotal()
    {
    }

    /**
     * Test attribute "tax_status"
     */
    public function testPropertyTaxStatus()
    {
    }
}
