<?php
/**
 * ProductExportJsonApiTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductExportJsonApiTest Class Doc Comment
 *
 * @category    Class
 * @description Added since version: 6.1.0.0
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductExportJsonApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductExportJsonApi"
     */
    public function testProductExportJsonApi()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "product_stream_id"
     */
    public function testPropertyProductStreamId()
    {
    }

    /**
     * Test attribute "storefront_sales_channel_id"
     */
    public function testPropertyStorefrontSalesChannelId()
    {
    }

    /**
     * Test attribute "sales_channel_id"
     */
    public function testPropertySalesChannelId()
    {
    }

    /**
     * Test attribute "sales_channel_domain_id"
     */
    public function testPropertySalesChannelDomainId()
    {
    }

    /**
     * Test attribute "currency_id"
     */
    public function testPropertyCurrencyId()
    {
    }

    /**
     * Test attribute "file_name"
     */
    public function testPropertyFileName()
    {
    }

    /**
     * Test attribute "access_key"
     */
    public function testPropertyAccessKey()
    {
    }

    /**
     * Test attribute "encoding"
     */
    public function testPropertyEncoding()
    {
    }

    /**
     * Test attribute "file_format"
     */
    public function testPropertyFileFormat()
    {
    }

    /**
     * Test attribute "include_variants"
     */
    public function testPropertyIncludeVariants()
    {
    }

    /**
     * Test attribute "generate_by_cronjob"
     */
    public function testPropertyGenerateByCronjob()
    {
    }

    /**
     * Test attribute "generated_at"
     */
    public function testPropertyGeneratedAt()
    {
    }

    /**
     * Test attribute "interval"
     */
    public function testPropertyInterval()
    {
    }

    /**
     * Test attribute "header_template"
     */
    public function testPropertyHeaderTemplate()
    {
    }

    /**
     * Test attribute "body_template"
     */
    public function testPropertyBodyTemplate()
    {
    }

    /**
     * Test attribute "footer_template"
     */
    public function testPropertyFooterTemplate()
    {
    }

    /**
     * Test attribute "paused_schedule"
     */
    public function testPropertyPausedSchedule()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "relationships"
     */
    public function testPropertyRelationships()
    {
    }
}
