<?php
/**
 * PromotionJsonApiRelationshipsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PromotionJsonApiRelationshipsTest Class Doc Comment
 *
 * @category    Class
 * @description PromotionJsonApiRelationships
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PromotionJsonApiRelationshipsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PromotionJsonApiRelationships"
     */
    public function testPromotionJsonApiRelationships()
    {
    }

    /**
     * Test attribute "setgroups"
     */
    public function testPropertySetgroups()
    {
    }

    /**
     * Test attribute "sales_channels"
     */
    public function testPropertySalesChannels()
    {
    }

    /**
     * Test attribute "discounts"
     */
    public function testPropertyDiscounts()
    {
    }

    /**
     * Test attribute "individual_codes"
     */
    public function testPropertyIndividualCodes()
    {
    }

    /**
     * Test attribute "persona_rules"
     */
    public function testPropertyPersonaRules()
    {
    }

    /**
     * Test attribute "persona_customers"
     */
    public function testPropertyPersonaCustomers()
    {
    }

    /**
     * Test attribute "order_rules"
     */
    public function testPropertyOrderRules()
    {
    }

    /**
     * Test attribute "cart_rules"
     */
    public function testPropertyCartRules()
    {
    }
}
