<?php
/**
 * RuleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RuleTest Class Doc Comment
 *
 * @category    Class
 * @description Added since version: 6.0.0.0
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RuleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Rule"
     */
    public function testRule()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "invalid"
     */
    public function testPropertyInvalid()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "module_types"
     */
    public function testPropertyModuleTypes()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "conditions"
     */
    public function testPropertyConditions()
    {
    }

    /**
     * Test attribute "product_prices"
     */
    public function testPropertyProductPrices()
    {
    }

    /**
     * Test attribute "shipping_method_prices"
     */
    public function testPropertyShippingMethodPrices()
    {
    }

    /**
     * Test attribute "shipping_method_price_calculations"
     */
    public function testPropertyShippingMethodPriceCalculations()
    {
    }

    /**
     * Test attribute "shipping_methods"
     */
    public function testPropertyShippingMethods()
    {
    }

    /**
     * Test attribute "payment_methods"
     */
    public function testPropertyPaymentMethods()
    {
    }

    /**
     * Test attribute "persona_promotions"
     */
    public function testPropertyPersonaPromotions()
    {
    }

    /**
     * Test attribute "order_promotions"
     */
    public function testPropertyOrderPromotions()
    {
    }

    /**
     * Test attribute "cart_promotions"
     */
    public function testPropertyCartPromotions()
    {
    }

    /**
     * Test attribute "promotion_discounts"
     */
    public function testPropertyPromotionDiscounts()
    {
    }

    /**
     * Test attribute "promotion_set_groups"
     */
    public function testPropertyPromotionSetGroups()
    {
    }

    /**
     * Test attribute "event_actions"
     */
    public function testPropertyEventActions()
    {
    }
}
