<?php
/**
 * SalesChannelJsonApiRelationshipsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SalesChannelJsonApiRelationshipsTest Class Doc Comment
 *
 * @category    Class
 * @description SalesChannelJsonApiRelationships
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SalesChannelJsonApiRelationshipsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SalesChannelJsonApiRelationships"
     */
    public function testSalesChannelJsonApiRelationships()
    {
    }

    /**
     * Test attribute "currencies"
     */
    public function testPropertyCurrencies()
    {
    }

    /**
     * Test attribute "languages"
     */
    public function testPropertyLanguages()
    {
    }

    /**
     * Test attribute "countries"
     */
    public function testPropertyCountries()
    {
    }

    /**
     * Test attribute "payment_methods"
     */
    public function testPropertyPaymentMethods()
    {
    }

    /**
     * Test attribute "shipping_methods"
     */
    public function testPropertyShippingMethods()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "customer_group"
     */
    public function testPropertyCustomerGroup()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "payment_method"
     */
    public function testPropertyPaymentMethod()
    {
    }

    /**
     * Test attribute "shipping_method"
     */
    public function testPropertyShippingMethod()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "orders"
     */
    public function testPropertyOrders()
    {
    }

    /**
     * Test attribute "customers"
     */
    public function testPropertyCustomers()
    {
    }

    /**
     * Test attribute "home_cms_page"
     */
    public function testPropertyHomeCmsPage()
    {
    }

    /**
     * Test attribute "domains"
     */
    public function testPropertyDomains()
    {
    }

    /**
     * Test attribute "system_configs"
     */
    public function testPropertySystemConfigs()
    {
    }

    /**
     * Test attribute "navigation_category"
     */
    public function testPropertyNavigationCategory()
    {
    }

    /**
     * Test attribute "footer_category"
     */
    public function testPropertyFooterCategory()
    {
    }

    /**
     * Test attribute "service_category"
     */
    public function testPropertyServiceCategory()
    {
    }

    /**
     * Test attribute "product_visibilities"
     */
    public function testPropertyProductVisibilities()
    {
    }

    /**
     * Test attribute "hreflang_default_domain"
     */
    public function testPropertyHreflangDefaultDomain()
    {
    }

    /**
     * Test attribute "mail_header_footer"
     */
    public function testPropertyMailHeaderFooter()
    {
    }

    /**
     * Test attribute "newsletter_recipients"
     */
    public function testPropertyNewsletterRecipients()
    {
    }

    /**
     * Test attribute "number_range_sales_channels"
     */
    public function testPropertyNumberRangeSalesChannels()
    {
    }

    /**
     * Test attribute "promotion_sales_channels"
     */
    public function testPropertyPromotionSalesChannels()
    {
    }

    /**
     * Test attribute "document_base_config_sales_channels"
     */
    public function testPropertyDocumentBaseConfigSalesChannels()
    {
    }

    /**
     * Test attribute "product_reviews"
     */
    public function testPropertyProductReviews()
    {
    }

    /**
     * Test attribute "seo_urls"
     */
    public function testPropertySeoUrls()
    {
    }

    /**
     * Test attribute "seo_url_templates"
     */
    public function testPropertySeoUrlTemplates()
    {
    }

    /**
     * Test attribute "main_categories"
     */
    public function testPropertyMainCategories()
    {
    }

    /**
     * Test attribute "product_exports"
     */
    public function testPropertyProductExports()
    {
    }

    /**
     * Test attribute "analytics"
     */
    public function testPropertyAnalytics()
    {
    }

    /**
     * Test attribute "customer_groups_registrations"
     */
    public function testPropertyCustomerGroupsRegistrations()
    {
    }

    /**
     * Test attribute "event_actions"
     */
    public function testPropertyEventActions()
    {
    }

    /**
     * Test attribute "landing_pages"
     */
    public function testPropertyLandingPages()
    {
    }

    /**
     * Test attribute "bound_customers"
     */
    public function testPropertyBoundCustomers()
    {
    }

    /**
     * Test attribute "wishlists"
     */
    public function testPropertyWishlists()
    {
    }
}
