<?php
/**
 * SalesChannelJsonApiTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SalesChannelJsonApiTest Class Doc Comment
 *
 * @category    Class
 * @description Added since version: 6.0.0.0
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SalesChannelJsonApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SalesChannelJsonApi"
     */
    public function testSalesChannelJsonApi()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type_id"
     */
    public function testPropertyTypeId()
    {
    }

    /**
     * Test attribute "language_id"
     */
    public function testPropertyLanguageId()
    {
    }

    /**
     * Test attribute "customer_group_id"
     */
    public function testPropertyCustomerGroupId()
    {
    }

    /**
     * Test attribute "currency_id"
     */
    public function testPropertyCurrencyId()
    {
    }

    /**
     * Test attribute "payment_method_id"
     */
    public function testPropertyPaymentMethodId()
    {
    }

    /**
     * Test attribute "shipping_method_id"
     */
    public function testPropertyShippingMethodId()
    {
    }

    /**
     * Test attribute "country_id"
     */
    public function testPropertyCountryId()
    {
    }

    /**
     * Test attribute "analytics_id"
     */
    public function testPropertyAnalyticsId()
    {
    }

    /**
     * Test attribute "navigation_category_id"
     */
    public function testPropertyNavigationCategoryId()
    {
    }

    /**
     * Test attribute "navigation_category_version_id"
     */
    public function testPropertyNavigationCategoryVersionId()
    {
    }

    /**
     * Test attribute "navigation_category_depth"
     */
    public function testPropertyNavigationCategoryDepth()
    {
    }

    /**
     * Test attribute "footer_category_id"
     */
    public function testPropertyFooterCategoryId()
    {
    }

    /**
     * Test attribute "footer_category_version_id"
     */
    public function testPropertyFooterCategoryVersionId()
    {
    }

    /**
     * Test attribute "service_category_id"
     */
    public function testPropertyServiceCategoryId()
    {
    }

    /**
     * Test attribute "service_category_version_id"
     */
    public function testPropertyServiceCategoryVersionId()
    {
    }

    /**
     * Test attribute "mail_header_footer_id"
     */
    public function testPropertyMailHeaderFooterId()
    {
    }

    /**
     * Test attribute "hreflang_default_domain_id"
     */
    public function testPropertyHreflangDefaultDomainId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "short_name"
     */
    public function testPropertyShortName()
    {
    }

    /**
     * Test attribute "tax_calculation_type"
     */
    public function testPropertyTaxCalculationType()
    {
    }

    /**
     * Test attribute "access_key"
     */
    public function testPropertyAccessKey()
    {
    }

    /**
     * Test attribute "configuration"
     */
    public function testPropertyConfiguration()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "hreflang_active"
     */
    public function testPropertyHreflangActive()
    {
    }

    /**
     * Test attribute "maintenance"
     */
    public function testPropertyMaintenance()
    {
    }

    /**
     * Test attribute "maintenance_ip_whitelist"
     */
    public function testPropertyMaintenanceIpWhitelist()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "payment_method_ids"
     */
    public function testPropertyPaymentMethodIds()
    {
    }

    /**
     * Test attribute "home_cms_page_id"
     */
    public function testPropertyHomeCmsPageId()
    {
    }

    /**
     * Test attribute "home_cms_page_version_id"
     */
    public function testPropertyHomeCmsPageVersionId()
    {
    }

    /**
     * Test attribute "home_slot_config"
     */
    public function testPropertyHomeSlotConfig()
    {
    }

    /**
     * Test attribute "home_enabled"
     */
    public function testPropertyHomeEnabled()
    {
    }

    /**
     * Test attribute "home_name"
     */
    public function testPropertyHomeName()
    {
    }

    /**
     * Test attribute "home_meta_title"
     */
    public function testPropertyHomeMetaTitle()
    {
    }

    /**
     * Test attribute "home_meta_description"
     */
    public function testPropertyHomeMetaDescription()
    {
    }

    /**
     * Test attribute "home_keywords"
     */
    public function testPropertyHomeKeywords()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "translated"
     */
    public function testPropertyTranslated()
    {
    }

    /**
     * Test attribute "relationships"
     */
    public function testPropertyRelationships()
    {
    }
}
