<?php
/**
 * ShippingMethodPriceJsonApiTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ShippingMethodPriceJsonApiTest Class Doc Comment
 *
 * @category    Class
 * @description Added since version: 6.0.0.0
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShippingMethodPriceJsonApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShippingMethodPriceJsonApi"
     */
    public function testShippingMethodPriceJsonApi()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "shipping_method_id"
     */
    public function testPropertyShippingMethodId()
    {
    }

    /**
     * Test attribute "rule_id"
     */
    public function testPropertyRuleId()
    {
    }

    /**
     * Test attribute "calculation"
     */
    public function testPropertyCalculation()
    {
    }

    /**
     * Test attribute "calculation_rule_id"
     */
    public function testPropertyCalculationRuleId()
    {
    }

    /**
     * Test attribute "quantity_start"
     */
    public function testPropertyQuantityStart()
    {
    }

    /**
     * Test attribute "quantity_end"
     */
    public function testPropertyQuantityEnd()
    {
    }

    /**
     * Test attribute "currency_price"
     */
    public function testPropertyCurrencyPrice()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "relationships"
     */
    public function testPropertyRelationships()
    {
    }
}
