<?php
/**
 * StateTransitionBody1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StateTransitionBody1Test Class Doc Comment
 *
 * @category    Class
 * @description StateTransitionBody1
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StateTransitionBody1Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StateTransitionBody1"
     */
    public function testStateTransitionBody1()
    {
    }

    /**
     * Test attribute "send_mail"
     */
    public function testPropertySendMail()
    {
    }

    /**
     * Test attribute "document_ids"
     */
    public function testPropertyDocumentIds()
    {
    }

    /**
     * Test attribute "media_ids"
     */
    public function testPropertyMediaIds()
    {
    }

    /**
     * Test attribute "state_field_name"
     */
    public function testPropertyStateFieldName()
    {
    }
}
