<?php
/**
 * WebhookEventLogTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WebhookEventLogTest Class Doc Comment
 *
 * @category    Class
 * @description Added since version: 6.4.1.0
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WebhookEventLogTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WebhookEventLog"
     */
    public function testWebhookEventLog()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "app_name"
     */
    public function testPropertyAppName()
    {
    }

    /**
     * Test attribute "webhook_name"
     */
    public function testPropertyWebhookName()
    {
    }

    /**
     * Test attribute "event_name"
     */
    public function testPropertyEventName()
    {
    }

    /**
     * Test attribute "delivery_status"
     */
    public function testPropertyDeliveryStatus()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "processing_time"
     */
    public function testPropertyProcessingTime()
    {
    }

    /**
     * Test attribute "app_version"
     */
    public function testPropertyAppVersion()
    {
    }

    /**
     * Test attribute "request_content"
     */
    public function testPropertyRequestContent()
    {
    }

    /**
     * Test attribute "response_content"
     */
    public function testPropertyResponseContent()
    {
    }

    /**
     * Test attribute "response_status_code"
     */
    public function testPropertyResponseStatusCode()
    {
    }

    /**
     * Test attribute "response_reason_phrase"
     */
    public function testPropertyResponseReasonPhrase()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }
}
