<?php
/**
 * AclRoleApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * AclRoleApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AclRoleApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createAclRole
     *
     * Create a new Acl Role resources.
     *
     */
    public function testCreateAclRole()
    {
    }

    /**
     * Test case for deleteAclRole
     *
     * Delete a Acl Role resource.
     *
     */
    public function testDeleteAclRole()
    {
    }

    /**
     * Test case for getAclRole
     *
     * Detailed information about a Acl Role resource.
     *
     */
    public function testGetAclRole()
    {
    }

    /**
     * Test case for getAclRoleList
     *
     * List with basic information of Acl Role resources.
     *
     */
    public function testGetAclRoleList()
    {
    }

    /**
     * Test case for updateAclRole
     *
     * Partially update information about a Acl Role resource.
     *
     */
    public function testUpdateAclRole()
    {
    }
}
