<?php
/**
 * EventActionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * EventActionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EventActionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createEventAction
     *
     * Create a new Event Action resources.
     *
     */
    public function testCreateEventAction()
    {
    }

    /**
     * Test case for deleteEventAction
     *
     * Delete a Event Action resource.
     *
     */
    public function testDeleteEventAction()
    {
    }

    /**
     * Test case for getEventAction
     *
     * Detailed information about a Event Action resource.
     *
     */
    public function testGetEventAction()
    {
    }

    /**
     * Test case for getEventActionList
     *
     * List with basic information of Event Action resources.
     *
     */
    public function testGetEventActionList()
    {
    }

    /**
     * Test case for updateEventAction
     *
     * Partially update information about a Event Action resource.
     *
     */
    public function testUpdateEventAction()
    {
    }
}
