<?php
/**
 * LandingPageApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * LandingPageApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LandingPageApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createLandingPage
     *
     * Create a new Landing Page resources.
     *
     */
    public function testCreateLandingPage()
    {
    }

    /**
     * Test case for deleteLandingPage
     *
     * Delete a Landing Page resource.
     *
     */
    public function testDeleteLandingPage()
    {
    }

    /**
     * Test case for getLandingPage
     *
     * Detailed information about a Landing Page resource.
     *
     */
    public function testGetLandingPage()
    {
    }

    /**
     * Test case for getLandingPageList
     *
     * List with basic information of Landing Page resources.
     *
     */
    public function testGetLandingPageList()
    {
    }

    /**
     * Test case for updateLandingPage
     *
     * Partially update information about a Landing Page resource.
     *
     */
    public function testUpdateLandingPage()
    {
    }
}
