<?php
/**
 * MediaThumbnailSizeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * MediaThumbnailSizeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MediaThumbnailSizeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createMediaThumbnailSize
     *
     * Create a new Media Thumbnail Size resources.
     *
     */
    public function testCreateMediaThumbnailSize()
    {
    }

    /**
     * Test case for deleteMediaThumbnailSize
     *
     * Delete a Media Thumbnail Size resource.
     *
     */
    public function testDeleteMediaThumbnailSize()
    {
    }

    /**
     * Test case for getMediaThumbnailSize
     *
     * Detailed information about a Media Thumbnail Size resource.
     *
     */
    public function testGetMediaThumbnailSize()
    {
    }

    /**
     * Test case for getMediaThumbnailSizeList
     *
     * List with basic information of Media Thumbnail Size resources.
     *
     */
    public function testGetMediaThumbnailSizeList()
    {
    }

    /**
     * Test case for updateMediaThumbnailSize
     *
     * Partially update information about a Media Thumbnail Size resource.
     *
     */
    public function testUpdateMediaThumbnailSize()
    {
    }
}
