<?php
/**
 * NumberRangeSalesChannelApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * NumberRangeSalesChannelApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NumberRangeSalesChannelApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createNumberRangeSalesChannel
     *
     * Create a new Number Range Sales Channel resources.
     *
     */
    public function testCreateNumberRangeSalesChannel()
    {
    }

    /**
     * Test case for deleteNumberRangeSalesChannel
     *
     * Delete a Number Range Sales Channel resource.
     *
     */
    public function testDeleteNumberRangeSalesChannel()
    {
    }

    /**
     * Test case for getNumberRangeSalesChannel
     *
     * Detailed information about a Number Range Sales Channel resource.
     *
     */
    public function testGetNumberRangeSalesChannel()
    {
    }

    /**
     * Test case for getNumberRangeSalesChannelList
     *
     * List with basic information of Number Range Sales Channel resources.
     *
     */
    public function testGetNumberRangeSalesChannelList()
    {
    }

    /**
     * Test case for updateNumberRangeSalesChannel
     *
     * Partially update information about a Number Range Sales Channel resource.
     *
     */
    public function testUpdateNumberRangeSalesChannel()
    {
    }
}
