<?php
/**
 * OrderDeliveryPositionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * OrderDeliveryPositionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderDeliveryPositionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createOrderDeliveryPosition
     *
     * Create a new Order Delivery Position resources.
     *
     */
    public function testCreateOrderDeliveryPosition()
    {
    }

    /**
     * Test case for deleteOrderDeliveryPosition
     *
     * Delete a Order Delivery Position resource.
     *
     */
    public function testDeleteOrderDeliveryPosition()
    {
    }

    /**
     * Test case for getOrderDeliveryPosition
     *
     * Detailed information about a Order Delivery Position resource.
     *
     */
    public function testGetOrderDeliveryPosition()
    {
    }

    /**
     * Test case for getOrderDeliveryPositionList
     *
     * List with basic information of Order Delivery Position resources.
     *
     */
    public function testGetOrderDeliveryPositionList()
    {
    }

    /**
     * Test case for updateOrderDeliveryPosition
     *
     * Partially update information about a Order Delivery Position resource.
     *
     */
    public function testUpdateOrderDeliveryPosition()
    {
    }
}
