<?php
/**
 * OrderDeliveryApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * OrderDeliveryApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderDeliveryApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createOrderDelivery
     *
     * Create a new Order Delivery resources.
     *
     */
    public function testCreateOrderDelivery()
    {
    }

    /**
     * Test case for deleteOrderDelivery
     *
     * Delete a Order Delivery resource.
     *
     */
    public function testDeleteOrderDelivery()
    {
    }

    /**
     * Test case for getOrderDelivery
     *
     * Detailed information about a Order Delivery resource.
     *
     */
    public function testGetOrderDelivery()
    {
    }

    /**
     * Test case for getOrderDeliveryList
     *
     * List with basic information of Order Delivery resources.
     *
     */
    public function testGetOrderDeliveryList()
    {
    }

    /**
     * Test case for updateOrderDelivery
     *
     * Partially update information about a Order Delivery resource.
     *
     */
    public function testUpdateOrderDelivery()
    {
    }
}
