<?php
/**
 * ProductSearchConfigFieldApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ProductSearchConfigFieldApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductSearchConfigFieldApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createProductSearchConfigField
     *
     * Create a new Product Search Config Field resources.
     *
     */
    public function testCreateProductSearchConfigField()
    {
    }

    /**
     * Test case for deleteProductSearchConfigField
     *
     * Delete a Product Search Config Field resource.
     *
     */
    public function testDeleteProductSearchConfigField()
    {
    }

    /**
     * Test case for getProductSearchConfigField
     *
     * Detailed information about a Product Search Config Field resource.
     *
     */
    public function testGetProductSearchConfigField()
    {
    }

    /**
     * Test case for getProductSearchConfigFieldList
     *
     * List with basic information of Product Search Config Field resources.
     *
     */
    public function testGetProductSearchConfigFieldList()
    {
    }

    /**
     * Test case for updateProductSearchConfigField
     *
     * Partially update information about a Product Search Config Field resource.
     *
     */
    public function testUpdateProductSearchConfigField()
    {
    }
}
