<?php
/**
 * StateMachineApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * StateMachineApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StateMachineApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createStateMachine
     *
     * Create a new State Machine resources.
     *
     */
    public function testCreateStateMachine()
    {
    }

    /**
     * Test case for deleteStateMachine
     *
     * Delete a State Machine resource.
     *
     */
    public function testDeleteStateMachine()
    {
    }

    /**
     * Test case for getStateMachine
     *
     * Detailed information about a State Machine resource.
     *
     */
    public function testGetStateMachine()
    {
    }

    /**
     * Test case for getStateMachineList
     *
     * List with basic information of State Machine resources.
     *
     */
    public function testGetStateMachineList()
    {
    }

    /**
     * Test case for updateStateMachine
     *
     * Partially update information about a State Machine resource.
     *
     */
    public function testUpdateStateMachine()
    {
    }
}
