<?php
/**
 * SystemOperationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * SystemOperationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SystemOperationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for clearCache
     *
     * Clear caches.
     *
     */
    public function testClearCache()
    {
    }

    /**
     * Test case for clearCacheAndScheduleWarmUp
     *
     * Clear and warm up caches.
     *
     */
    public function testClearCacheAndScheduleWarmUp()
    {
    }

    /**
     * Test case for clearContainerCache
     *
     * Clear container caches.
     *
     */
    public function testClearContainerCache()
    {
    }

    /**
     * Test case for clearOldCacheFolders
     *
     * Clear old cache folders.
     *
     */
    public function testClearOldCacheFolders()
    {
    }

    /**
     * Test case for consumeMessages
     *
     * Consume messages from the message queue..
     *
     */
    public function testConsumeMessages()
    {
    }

    /**
     * Test case for getMinRunInterval
     *
     * Get the minimum schedules task interval.
     *
     */
    public function testGetMinRunInterval()
    {
    }

    /**
     * Test case for index
     *
     * Run indexer.
     *
     */
    public function testIndex()
    {
    }

    /**
     * Test case for indexing
     *
     * Run indexer.
     *
     */
    public function testIndexing()
    {
    }

    /**
     * Test case for info
     *
     * Get cache information.
     *
     */
    public function testInfo()
    {
    }

    /**
     * Test case for iterate
     *
     * Iterate an indexer.
     *
     */
    public function testIterate()
    {
    }

    /**
     * Test case for runScheduledTasks
     *
     * Run scheduled tasks..
     *
     */
    public function testRunScheduledTasks()
    {
    }
}
