<?php
/**
 * ThemeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ThemeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ThemeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createTheme
     *
     * Create a new Theme resources.
     *
     */
    public function testCreateTheme()
    {
    }

    /**
     * Test case for deleteTheme
     *
     * Delete a Theme resource.
     *
     */
    public function testDeleteTheme()
    {
    }

    /**
     * Test case for getTheme
     *
     * Detailed information about a Theme resource.
     *
     */
    public function testGetTheme()
    {
    }

    /**
     * Test case for getThemeList
     *
     * List with basic information of Theme resources.
     *
     */
    public function testGetThemeList()
    {
    }

    /**
     * Test case for updateTheme
     *
     * Partially update information about a Theme resource.
     *
     */
    public function testUpdateTheme()
    {
    }
}
