<?php
/**
 * UserConfigApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.4.9999999.9999999-dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * UserConfigApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserConfigApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createUserConfig
     *
     * Create a new User Config resources.
     *
     */
    public function testCreateUserConfig()
    {
    }

    /**
     * Test case for deleteUserConfig
     *
     * Delete a User Config resource.
     *
     */
    public function testDeleteUserConfig()
    {
    }

    /**
     * Test case for getUserConfig
     *
     * Detailed information about a User Config resource.
     *
     */
    public function testGetUserConfig()
    {
    }

    /**
     * Test case for getUserConfigList
     *
     * List with basic information of User Config resources.
     *
     */
    public function testGetUserConfigList()
    {
    }

    /**
     * Test case for updateUserConfig
     *
     * Partially update information about a User Config resource.
     *
     */
    public function testUpdateUserConfig()
    {
    }
}
